/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class DATAMITRAJUAL extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public DATAMITRAJUAL() {
        connect();
        initComponents();
        showTable();
        setLocationRelativeTo(null);

        TableMITRAJUAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TableMITRAJUAL.getSelectedRow();
                if (row >= 0) {
                    String id = TableMITRAJUAL.getValueAt(row, 0).toString();
                    String nama = TableMITRAJUAL.getValueAt(row, 1).toString();
                    String alamat = TableMITRAJUAL.getValueAt(row, 2).toString();
                    String telpon = TableMITRAJUAL.getValueAt(row, 3).toString();
                    String jenis = TableMITRAJUAL.getValueAt(row, 4).toString();
                }
            }
        });
    }

    public void showTable() {
        try {
            em.getEntityManagerFactory().getCache().evictAll();
            em.clear();

            List<MitraJual> hasil = em.createNamedQuery("MitraJual.findAll", MitraJual.class)
                    .getResultList();

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{
                        "ID Mitra", "Nama Mitra", "Alamat", "Telpon", "Jenis Kerja Sama"
                    }, 0
            );

            for (MitraJual m : hasil) {
                model.addRow(new Object[]{
                    m.getIdMitra(),
                    m.getNamaMitra(),
                    m.getAlamatMitra(),
                    m.getTelponMitra(),
                    m.getJenisKerjaSama()
                });
            }

            TableMITRAJUAL.setModel(model);

            DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < TableMITRAJUAL.getColumnCount(); i++) {
                TableMITRAJUAL.getColumnModel().getColumn(i).setCellRenderer(center);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableMITRAJUAL = new javax.swing.JTable();
        jButtonEDIT = new javax.swing.JButton();
        jButtonTAMBAH1 = new javax.swing.JButton();
        jButtonHAPUS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableMITRAJUAL.setBackground(new java.awt.Color(255, 255, 255));
        TableMITRAJUAL.setForeground(new java.awt.Color(0, 0, 0));
        TableMITRAJUAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableMITRAJUAL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 870, 300));

        jButtonEDIT.setBackground(new java.awt.Color(0, 51, 0));
        jButtonEDIT.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonEDIT.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEDIT.setText("EDIT");
        jButtonEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, 30));

        jButtonTAMBAH1.setBackground(new java.awt.Color(0, 51, 0));
        jButtonTAMBAH1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonTAMBAH1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTAMBAH1.setText("TAMBAH");
        jButtonTAMBAH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTAMBAH1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTAMBAH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 100, 30));

        jButtonHAPUS.setBackground(new java.awt.Color(0, 51, 0));
        jButtonHAPUS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHAPUS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHAPUS.setText("HAPUS");
        jButtonHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANK SAMPAH - MENU PETUGAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA MITRA JUAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 148.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITActionPerformed
        int row = TableMITRAJUAL.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu di tabel!");
            return;
        }

        Integer id = Integer.parseInt(TableMITRAJUAL.getValueAt(row, 0).toString());
        String nama = TableMITRAJUAL.getValueAt(row, 1).toString();
        String alamat = TableMITRAJUAL.getValueAt(row, 2).toString();
        String noTelp = TableMITRAJUAL.getValueAt(row, 3).toString();
        String jenisKerjaSama = TableMITRAJUAL.getValueAt(row, 4).toString();

        editMITRAJUAL dialog = new editMITRAJUAL(this, true, id, nama, alamat, noTelp, jenisKerjaSama);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        showTable();

    }//GEN-LAST:event_jButtonEDITActionPerformed

    private void jButtonTAMBAH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTAMBAH1ActionPerformed
        tambahMITRAJUAL dialog = new tambahMITRAJUAL(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable();
    }//GEN-LAST:event_jButtonTAMBAH1ActionPerformed

    private void jButtonHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHAPUSActionPerformed
        int[] rows = TableMITRAJUAL.getSelectedRows(); // ambil semua baris yang dipilih
        if (rows.length == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data Mitra Jual dulu di tabel!");
            return;
        }

        String[] idMitraLama = new String[rows.length];
        String[] namaMitraLama = new String[rows.length];
        String[] alamatLama = new String[rows.length];
        String[] noTelpLama = new String[rows.length];

        for (int i = 0; i < rows.length; i++) {
            idMitraLama[i] = TableMITRAJUAL.getValueAt(rows[i], 0).toString();   // kolom ID
            namaMitraLama[i] = TableMITRAJUAL.getValueAt(rows[i], 1).toString(); // kolom Nama Mitra
            alamatLama[i] = TableMITRAJUAL.getValueAt(rows[i], 2).toString();    // kolom Alamat
            noTelpLama[i] = TableMITRAJUAL.getValueAt(rows[i], 3).toString();    // kolom No. Telp
        }

        hapusMITRAJUAL dialog = new hapusMITRAJUAL(this, true, idMitraLama, namaMitraLama, alamatLama, noTelpLama);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable();


    }//GEN-LAST:event_jButtonHAPUSActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        MENUPETUGAS z = new MENUPETUGAS();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new KELOLAJENISSAMPAH().setVisible(true);
////            }
////        });
////    }
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMITRAJUAL;
    private javax.swing.JButton jButtonEDIT;
    private javax.swing.JButton jButtonHAPUS;
    private javax.swing.JButton jButtonTAMBAH1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
