/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import java.math.BigInteger;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class editMITRAJUAL extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    // Data lama
    private Integer idLama;
    private String namaLama, alamatLama, telponLama, jenisKerjaSamaLama;

    public editMITRAJUAL(DATAMITRAJUAL parent, boolean modal,
            Integer idLama, String namaLama,
            String alamatLama, String telponLama,
            String jenisKerjaSamaLama) {
        super(parent, modal);
        initComponents();
        connect();
        loadComboJenisKerjaSama();

        // set data lama ke field
        this.idLama = idLama;
        this.namaLama = namaLama;
        this.alamatLama = alamatLama;
        this.telponLama = telponLama;
        this.jenisKerjaSamaLama = jenisKerjaSamaLama;

        textIDMITRAJUAL.setText(String.valueOf(idLama));
        textNAMAMITRA1.setText(namaLama);
        textALAMATMITRA.setText(alamatLama);
        textHARGAPERKG.setText(telponLama);
        jComboBoxJenisKerjaSama.setSelectedItem(jenisKerjaSamaLama);

        setLocationRelativeTo(null);
    }

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    private void loadComboJenisKerjaSama() {
        jComboBoxJenisKerjaSama.removeAllItems();
        jComboBoxJenisKerjaSama.addItem("Reseller");
        jComboBoxJenisKerjaSama.addItem("Distributor");
        jComboBoxJenisKerjaSama.addItem("Retail");
        jComboBoxJenisKerjaSama.addItem("Pabrik Plastik");
        jComboBoxJenisKerjaSama.addItem("Pengepul Lokal");
        jComboBoxJenisKerjaSama.setEditable(true);
    }

    private boolean validasiInput() {
        if (textNAMAMITRA1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Mitra harus diisi");
            textNAMAMITRA1.requestFocus();
            return false;
        }
        if (textALAMATMITRA.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat Mitra harus diisi");
            textALAMATMITRA.requestFocus();
            return false;
        }
        if (textHARGAPERKG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Telepon Mitra harus diisi");
            textHARGAPERKG.requestFocus();
            return false;
        }
        if (jComboBoxJenisKerjaSama.getSelectedItem() == null
                || jComboBoxJenisKerjaSama.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jenis Kerja Sama harus diisi");
            jComboBoxJenisKerjaSama.requestFocus();
            return false;
        }
        return true;
    }

    private void bersih() {
        textIDMITRAJUAL.setText("");
        textNAMAMITRA1.setText("");
        textALAMATMITRA.setText("");
        textHARGAPERKG.setText("");
        jComboBoxJenisKerjaSama.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textHARGAPERKG = new javax.swing.JTextField();
        textALAMATMITRA = new javax.swing.JTextField();
        textIDMITRAJUAL = new javax.swing.JTextField();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxJenisKerjaSama = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNAMAMITRA1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textHARGAPERKG.setBackground(new java.awt.Color(204, 255, 153));
        textHARGAPERKG.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textHARGAPERKG.setForeground(new java.awt.Color(0, 0, 0));
        textHARGAPERKG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textHARGAPERKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHARGAPERKGActionPerformed(evt);
            }
        });
        getContentPane().add(textHARGAPERKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 420, 30));

        textALAMATMITRA.setBackground(new java.awt.Color(204, 255, 153));
        textALAMATMITRA.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textALAMATMITRA.setForeground(new java.awt.Color(0, 0, 0));
        textALAMATMITRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textALAMATMITRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textALAMATMITRAActionPerformed(evt);
            }
        });
        getContentPane().add(textALAMATMITRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 420, 30));

        textIDMITRAJUAL.setBackground(new java.awt.Color(204, 255, 153));
        textIDMITRAJUAL.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textIDMITRAJUAL.setForeground(new java.awt.Color(0, 0, 0));
        textIDMITRAJUAL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textIDMITRAJUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDMITRAJUALActionPerformed(evt);
            }
        });
        getContentPane().add(textIDMITRAJUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, 30));

        jButtonSIMPAN.setBackground(new java.awt.Color(0, 51, 0));
        jButtonSIMPAN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 130, 40));

        jButtonBATAL.setBackground(new java.awt.Color(0, 51, 0));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBATAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Alamat Mitra");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID Mitra Jual");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jenis Kerja sama");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        jComboBoxJenisKerjaSama.setBackground(new java.awt.Color(204, 255, 153));
        jComboBoxJenisKerjaSama.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxJenisKerjaSama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(jComboBoxJenisKerjaSama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 420, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Mitra");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NO Telepon");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BANK SAMPAH - KELOLA MITRA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 127, 80));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDIT DATA MITRA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        textNAMAMITRA1.setBackground(new java.awt.Color(204, 255, 153));
        textNAMAMITRA1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textNAMAMITRA1.setForeground(new java.awt.Color(0, 0, 0));
        textNAMAMITRA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textNAMAMITRA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNAMAMITRA1ActionPerformed(evt);
            }
        });
        getContentPane().add(textNAMAMITRA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 420, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 149.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHARGAPERKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHARGAPERKGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHARGAPERKGActionPerformed

    private void textALAMATMITRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textALAMATMITRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textALAMATMITRAActionPerformed

    private void textIDMITRAJUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDMITRAJUALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDMITRAJUALActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        if (!validasiInput()) {
            return;
        }

        try {
            em.getTransaction().begin();

            MitraJual m = em.find(MitraJual.class, idLama);
            if (m != null) {
                m.setNamaMitra(textNAMAMITRA1.getText().trim());
                m.setAlamatMitra(textALAMATMITRA.getText().trim());
                m.setTelponMitra(textHARGAPERKG.getText().trim());
                m.setJenisKerjaSama(jComboBoxJenisKerjaSama.getSelectedItem().toString().trim());

                em.getTransaction().commit();
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                this.dispose();
            } else {
                em.getTransaction().rollback();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan.");
            }

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
            e.printStackTrace();
        };
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        bersih();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void textNAMAMITRA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNAMAMITRA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNAMAMITRA1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                insertkelolanasabah dialog = new insertkelolanasabah(new javax.swing.JFrame(), true);
////                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
////                    @Override
////                    public void windowClosing(java.awt.event.WindowEvent e) {
////                        System.exit(0);
////                    }
////                });
////                dialog.setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JComboBox<String> jComboBoxJenisKerjaSama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textALAMATMITRA;
    private javax.swing.JTextField textHARGAPERKG;
    private javax.swing.JTextField textIDMITRAJUAL;
    private javax.swing.JTextField textNAMAMITRA1;
    // End of variables declaration//GEN-END:variables
}
