/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Window;
import java.io.FileWriter;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jnafilechooser.api.JnaFileChooser;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class KELOLAJENISSAMPAH extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    String idNasabahLama, namaLama, alamatLama, teleponLama, usernameLama,
            passwordLama, namaIbuLama, idSaldoLama;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public KELOLAJENISSAMPAH() {
        connect();
        initComponents();
        showTable();
        setLocationRelativeTo(null);

        TableKELOLASAMPAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TableKELOLASAMPAH.getSelectedRow();
                if (row >= 0) {
                    String id = TableKELOLASAMPAH.getValueAt(row, 0).toString();
                    String namaSampah = TableKELOLASAMPAH.getValueAt(row, 1).toString();
                    String kategori = TableKELOLASAMPAH.getValueAt(row, 2).toString();
                    String hargaPerKg = TableKELOLASAMPAH.getValueAt(row, 3).toString();
                }
            }
        });
    }

    /**
     * Creates new form LOGIN
     */
    public void showTable() {
        try {
            em.getEntityManagerFactory().getCache().evictAll();
            em.clear();

            List<JenisSampah> hasil = em.createNamedQuery("JenisSampah.findAll", JenisSampah.class)
                    .getResultList();

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{
                        "ID Jenis Sampah", "Nama Sampah", "Kategori", "Harga per Kg"
                    }, 0
            );

            for (JenisSampah j : hasil) {
                model.addRow(new Object[]{
                    j.getIdJenissampah(),
                    j.getNamaSampah(),
                    j.getKategori(),
                    j.getHargaPerKg()
                });
            }

            TableKELOLASAMPAH.setModel(model);

            DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(JLabel.CENTER);

            for (int i = 0; i < TableKELOLASAMPAH.getColumnCount(); i++) {
                TableKELOLASAMPAH.getColumnModel().getColumn(i).setCellRenderer(center);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    public void exportToCSV(javax.swing.JTable table, String filePath) {
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            FileWriter csv = new FileWriter(filePath);

            for (int i = 0; i < model.getColumnCount(); i++) {
                csv.write(model.getColumnName(i) + (i < model.getColumnCount() - 1 ? "," : ""));
            }
            csv.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Object value = model.getValueAt(i, j);
                    csv.write((value != null ? value.toString() : "")
                            + (j < model.getColumnCount() - 1 ? "," : ""));
                }
                csv.write("\n");
            }

            csv.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke: " + filePath);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ekspor: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableKELOLASAMPAH = new javax.swing.JTable();
        jButtonEDIT = new javax.swing.JButton();
        jButtonTAMBAH1 = new javax.swing.JButton();
        jButtonHAPUS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonCETAK = new javax.swing.JButton();
        jButtonUNDUHDATA = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableKELOLASAMPAH.setBackground(new java.awt.Color(255, 255, 255));
        TableKELOLASAMPAH.setForeground(new java.awt.Color(0, 0, 0));
        TableKELOLASAMPAH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableKELOLASAMPAH);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 870, 300));

        jButtonEDIT.setBackground(new java.awt.Color(0, 51, 0));
        jButtonEDIT.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonEDIT.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEDIT.setText("EDIT");
        jButtonEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, 30));

        jButtonTAMBAH1.setBackground(new java.awt.Color(0, 51, 0));
        jButtonTAMBAH1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonTAMBAH1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTAMBAH1.setText("TAMBAH");
        jButtonTAMBAH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTAMBAH1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTAMBAH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 100, 30));

        jButtonHAPUS.setBackground(new java.awt.Color(0, 51, 0));
        jButtonHAPUS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHAPUS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHAPUS.setText("HAPUS");
        jButtonHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANK SAMPAH - MENU PETUGAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KELOLA JENIS SAMPAH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, 40));

        jButtonCETAK.setBackground(new java.awt.Color(51, 102, 0));
        jButtonCETAK.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonCETAK.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCETAK.setText("CETAK");
        jButtonCETAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCETAKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCETAK, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 120, 30));

        jButtonUNDUHDATA.setBackground(new java.awt.Color(0, 51, 0));
        jButtonUNDUHDATA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonUNDUHDATA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUNDUHDATA.setText("UNDUH DATA");
        jButtonUNDUHDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUNDUHDATAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUNDUHDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 120, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 148.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITActionPerformed
        int row = TableKELOLASAMPAH.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu di tabel!");
            return;
        }

        String id = TableKELOLASAMPAH.getValueAt(row, 0).toString();
        String nama = TableKELOLASAMPAH.getValueAt(row, 1).toString();
        String kategori = TableKELOLASAMPAH.getValueAt(row, 2).toString();
        String harga = TableKELOLASAMPAH.getValueAt(row, 3).toString();

        editKELOLAHJENISSAMPAH dialog = new editKELOLAHJENISSAMPAH(this, true, id, nama, kategori, harga);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        showTable();
    }//GEN-LAST:event_jButtonEDITActionPerformed

    private void jButtonTAMBAH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTAMBAH1ActionPerformed
        tambahKELOLAHJENISSAMPAH dialog = new tambahKELOLAHJENISSAMPAH(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable();
    }//GEN-LAST:event_jButtonTAMBAH1ActionPerformed

    private void jButtonHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHAPUSActionPerformed
        int[] rows = TableKELOLASAMPAH.getSelectedRows(); // ambil semua baris yang dipilih
        if (rows.length == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu di tabel!");
            return;
        }
        String[] idJenisSampahLama = new String[rows.length];
        String[] namaSampahLama = new String[rows.length];
        String[] kategoriLama = new String[rows.length];
        String[] hargaPerKgLama = new String[rows.length];

        for (int i = 0; i < rows.length; i++) {
            idJenisSampahLama[i] = TableKELOLASAMPAH.getValueAt(rows[i], 0).toString();
            namaSampahLama[i] = TableKELOLASAMPAH.getValueAt(rows[i], 1).toString();
            kategoriLama[i] = TableKELOLASAMPAH.getValueAt(rows[i], 2).toString();
            hargaPerKgLama[i] = TableKELOLASAMPAH.getValueAt(rows[i], 3).toString();
        }

        hapusKELOLAHJENISSAMPAH dialog = new hapusKELOLAHJENISSAMPAH(this, true, idJenisSampahLama, namaSampahLama, kategoriLama, hargaPerKgLama);
        dialog.setLocationRelativeTo(this); // tampil di tengah layar
        dialog.setVisible(true);

        showTable();

    }//GEN-LAST:event_jButtonHAPUSActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        MENUPETUGAS z = new MENUPETUGAS();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonCETAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCETAKActionPerformed
        try {
            String path = "src/Login/DATASAMPAH.jasper";
            HashMap<String, Object> parameters = new HashMap<>();

            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BANK_SAMPAH", "postgres", "BISMILLAH");

            JasperPrint jprint = JasperFillManager.fillReport(path, parameters, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setSize(800, 600);
            jviewer.setLocationRelativeTo(this);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonCETAKActionPerformed

    private void jButtonUNDUHDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUNDUHDATAActionPerformed
        try {
            if (TableKELOLASAMPAH.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Tidak ada data untuk diekspor!");
                return;
            }

            JnaFileChooser chooser = new JnaFileChooser();
            chooser.setMode(JnaFileChooser.Mode.Files);
            chooser.setTitle("Simpan Data Sampah");
            chooser.setDefaultFileName("Data_Sampah");
            chooser.setMultiSelectionEnabled(false);

            Window window = null;
            boolean action = chooser.showSaveDialog(window);

            if (action) {
                String fileString = chooser.getSelectedFile().getAbsolutePath();
                if (!fileString.toLowerCase().endsWith(".csv")) {
                    fileString += ".csv";
                }

                exportToCSV(TableKELOLASAMPAH, fileString);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ekspor: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUNDUHDATAActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KELOLAJENISSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new KELOLAJENISSAMPAH().setVisible(true);
////            }
////        });
////    }
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableKELOLASAMPAH;
    private javax.swing.JButton jButtonCETAK;
    private javax.swing.JButton jButtonEDIT;
    private javax.swing.JButton jButtonHAPUS;
    private javax.swing.JButton jButtonTAMBAH1;
    private javax.swing.JButton jButtonUNDUHDATA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
