/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LUPASANDIPETUGAS extends javax.swing.JFrame {

    /**
     * Creates new form UBAHSALAH2
     */
    public LUPASANDIPETUGAS() {
        initComponents();
        jLabelPASS.setVisible(false);
        jButtonUBAH.setVisible(false);
        jTextFieldPASS.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUSER = new javax.swing.JTextField();
        jLabelPASS = new javax.swing.JLabel();
        jTextFieldPASS = new javax.swing.JTextField();
        jButtonCARI = new javax.swing.JButton();
        jButtonUBAH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonKEMBALI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("UBAH KATA SANDI");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        jTextFieldUSER.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUSERActionPerformed(evt);
            }
        });

        jLabelPASS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPASS.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPASS.setText("Ubah Kata Sandi");

        jTextFieldPASS.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPASSMouseClicked(evt);
            }
        });
        jTextFieldPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPASSActionPerformed(evt);
            }
        });

        jButtonCARI.setBackground(new java.awt.Color(51, 102, 0));
        jButtonCARI.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonCARI.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCARI.setText("cari");
        jButtonCARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCARIActionPerformed(evt);
            }
        });

        jButtonUBAH.setBackground(new java.awt.Color(204, 255, 153));
        jButtonUBAH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonUBAH.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUBAH.setText("UBAH");
        jButtonUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUBAHActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N

        jButtonKEMBALI.setBackground(new java.awt.Color(255, 0, 51));
        jButtonKEMBALI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonKEMBALI.setForeground(new java.awt.Color(0, 0, 0));
        jButtonKEMBALI.setText("KEMBALI");
        jButtonKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKEMBALIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabelPASS)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonKEMBALI)
                                        .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUBAH)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCARI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUSER, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPASS)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUBAH)
                            .addComponent(jButtonKEMBALI))
                        .addGap(61, 61, 61))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUSERActionPerformed
        if (jTextFieldUSER.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            jButtonCARI.doClick();
        }
    }//GEN-LAST:event_jTextFieldUSERActionPerformed

    private void jTextFieldPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPASSActionPerformed
        jButtonCARI.doClick();
    }//GEN-LAST:event_jTextFieldPASSActionPerformed

    private void jButtonCARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCARIActionPerformed

        String username = jTextFieldUSER.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi nama pengguna terlebih dahulu!");
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        try {
            TypedQuery<Petugas> query = em.createQuery(
                    "SELECT p FROM Petugas p WHERE p.usernamePetugas = :u", Petugas.class);
            query.setParameter("u", username);

            Petugas petugas;
            try {
                petugas = query.getSingleResult();
            } catch (javax.persistence.NoResultException ex) {
                petugas = null;
            }

            if (petugas != null) {
                // Minta input nama ibu
                String inputIbu = JOptionPane.showInputDialog(
                        this,
                        "Nama Pengguna ditemukan! Masukkan Nama Ibu untuk konfirmasi:",
                        "Konfirmasi Keamanan",
                        JOptionPane.QUESTION_MESSAGE
                );
                if (inputIbu == null) {
                    return;
                }

                if (!inputIbu.equalsIgnoreCase(petugas.getNamaIbu())) {
                    JOptionPane.showMessageDialog(this, "Nama Ibu tidak sesuai!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Verifikasi berhasil! Silakan ubah kata sandi.", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                jLabelPASS.setVisible(true);
                jTextFieldPASS.setVisible(true);
                jButtonUBAH.setVisible(true);
                jTextFieldUSER.setEditable(false);
                jTextFieldPASS.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Nama Pengguna tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan koneksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButtonCARIActionPerformed

    private void jButtonUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUBAHActionPerformed

        String newPass = jTextFieldPASS.getText().trim();
        if (newPass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi kata sandi baru terlebih dahulu");
            return;
        }

        String username = jTextFieldUSER.getText().trim();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        try {
            TypedQuery<Petugas> query = em.createQuery(
                    "SELECT p FROM Petugas p WHERE p.usernamePetugas = :u", Petugas.class);
            query.setParameter("u", username);

            Petugas petugas;
            try {
                petugas = query.getSingleResult();
            } catch (javax.persistence.NoResultException ex) {
                petugas = null;
            }

            if (petugas != null) {
                em.getTransaction().begin();
                petugas.setPasswordPetugas(newPass);
                em.merge(petugas);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "kata sandi berhasil diubah! Silakan Masuk kembali.");
                this.dispose();
                new MASUKPETUGAS(null, true).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Akun tidak ditemukan!");
            }

        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButtonUBAHActionPerformed

    private void jTextFieldPASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPASSMouseClicked
        jButtonUBAH.doClick();
    }//GEN-LAST:event_jTextFieldPASSMouseClicked

    private void jButtonKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKEMBALIActionPerformed
        this.dispose();
        MASUKPETUGAS m = new MASUKPETUGAS(null, true);
        m.setVisible(true);

    }//GEN-LAST:event_jButtonKEMBALIActionPerformed

    /**
     * @param args the command line arguments
     */
//      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCARI;
    private javax.swing.JButton jButtonKEMBALI;
    private javax.swing.JButton jButtonUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPASS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPASS;
    private javax.swing.JTextField jTextFieldUSER;
    // End of variables declaration//GEN-END:variables
}
