/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MASUKNASABAH extends javax.swing.JDialog {

    private ROLEMASUK parent;
    private static int idNasabah;

    /**
     * Creates new form DAFTAR
     */
    public MASUKNASABAH(ROLEMASUK parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
    }

    public static void setIdNasabah(int id) {
        idNasabah = id;
    }

    public static int getIdNasabah() {
        return idNasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonMASUKNASABAH = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNAMANASABAH = new javax.swing.JTextField();
        jCheckBoxPASS = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelLUPASANDI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Masukkan nama dan kata sandi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MASUK SEBAGAI NASABAH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kata Sandi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        jButtonMASUKNASABAH.setBackground(new java.awt.Color(0, 102, 51));
        jButtonMASUKNASABAH.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jButtonMASUKNASABAH.setForeground(new java.awt.Color(204, 255, 153));
        jButtonMASUKNASABAH.setText("MASUK");
        jButtonMASUKNASABAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMASUKNASABAHActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMASUKNASABAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nama Pengguna");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jTextFieldNAMANASABAH.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldNAMANASABAH.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jTextFieldNAMANASABAH.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNAMANASABAH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldNAMANASABAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNAMANASABAHActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNAMANASABAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 40));

        jCheckBoxPASS.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPASS.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxPASS.setText("Tampilkan kata sandi");
        jCheckBoxPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPASSActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 153));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 270, 40));

        jLabelLUPASANDI.setBackground(new java.awt.Color(0, 0, 0));
        jLabelLUPASANDI.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabelLUPASANDI.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLUPASANDI.setText("Lupa Kata Sandi ?");
        jLabelLUPASANDI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLUPASANDIMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLUPASANDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMASUKNASABAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMASUKNASABAHActionPerformed

        if (jTextFieldNAMANASABAH.getText().equals("") || new String(jPasswordField1.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dan password terlebih dahulu!");
            return; // Berhenti di sini
        }

        // 2. Buka Koneksi Database
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        try {
            String user = jTextFieldNAMANASABAH.getText();
            String pw = new String(jPasswordField1.getPassword());

            Nasabah n = em.createQuery(
                    "SELECT n FROM Nasabah n WHERE n.usernameNasabah = :u", Nasabah.class)
                    .setParameter("u", user)
                    .getSingleResult();

            if (n.getPasswordNasabah().equals(pw)) {

                JOptionPane.showMessageDialog(null, "Selamat datang " + n.getNamaNasabah());

                // Buka Menu Nasabah
                MENUNASABAH mn = new MENUNASABAH(n.getIdNasabah());
                mn.setVisible(true);

                // Tutup Login & Parent (Role Masuk)
                this.dispose();
                if (parent != null) {
                    parent.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Password salah!");
                jPasswordField1.setText("");
            }

        } catch (NoResultException e) {
            JOptionPane.showMessageDialog(null, "Username tidak ditemukan!");
            jTextFieldNAMANASABAH.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } finally {

            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }
    }//GEN-LAST:event_jButtonMASUKNASABAHActionPerformed

    private void jTextFieldNAMANASABAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNAMANASABAHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNAMANASABAHActionPerformed

    private void jCheckBoxPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPASSActionPerformed
        if (jCheckBoxPASS.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPASSActionPerformed

    private void jLabelLUPASANDIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLUPASANDIMouseClicked
        LUPASANDINASABAH l = new LUPASANDINASABAH();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLUPASANDIMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMASUKNASABAH;
    private javax.swing.JCheckBox jCheckBoxPASS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLUPASANDI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldNAMANASABAH;
    // End of variables declaration//GEN-END:variables
}
