/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MASUKPETUGAS extends javax.swing.JDialog {

    /**
     * Creates new form DAFTAR
     */
    private ROLEMASUK parent;

    public MASUKPETUGAS(ROLEMASUK parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
    }

    private void bersih() {
        jTextFieldNAMAPETUGAS.setText("");
        jTextFieldPASSPETUGAS.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLUPASANDI = new javax.swing.JLabel();
        jButtonMASUKPETUGAS = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNAMAPETUGAS = new javax.swing.JTextField();
        jTextFieldPASSPETUGAS = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxPASS = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Masukkan Nama dan Kata Sandi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MASUK SEBAGAI PETUGAS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabelLUPASANDI.setBackground(new java.awt.Color(0, 0, 0));
        jLabelLUPASANDI.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabelLUPASANDI.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLUPASANDI.setText("Lupa Kata Sandi ?");
        jLabelLUPASANDI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLUPASANDIMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLUPASANDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, 20));

        jButtonMASUKPETUGAS.setBackground(new java.awt.Color(0, 102, 51));
        jButtonMASUKPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jButtonMASUKPETUGAS.setForeground(new java.awt.Color(204, 255, 153));
        jButtonMASUKPETUGAS.setText("MASUK");
        jButtonMASUKPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMASUKPETUGASActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMASUKPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nama Pengguna");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jTextFieldNAMAPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldNAMAPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jTextFieldNAMAPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNAMAPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldNAMAPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNAMAPETUGASActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNAMAPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 40));

        jTextFieldPASSPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldPASSPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPASSPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPASSPETUGASActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPASSPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 270, 40));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Kata Sandi");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        jCheckBoxPASS.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPASS.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxPASS.setText("Tampilkan kata sandi");
        jCheckBoxPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPASSActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMASUKPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMASUKPETUGASActionPerformed
        if (jTextFieldNAMAPETUGAS.getText().equals("")
                || new String(jTextFieldPASSPETUGAS.getPassword()).equals("")) {

            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");

        } else {

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            EntityManager em = emf.createEntityManager();

            String user = jTextFieldNAMAPETUGAS.getText();
            String pw = new String(jTextFieldPASSPETUGAS.getPassword());

            try {
                Petugas y = em.createQuery(
                        "SELECT p FROM Petugas p WHERE p.usernamePetugas = :u", Petugas.class)
                        .setParameter("u", user)
                        .getSingleResult();

                if (y.getPasswordPetugas().equals(pw)) {
                    JOptionPane.showMessageDialog(null, "Selamat datang " + user);
                    new MENUPETUGAS().setVisible(true);

                    this.dispose();      // tutup dialog
                    parent.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Password salah!");
                    jTextFieldPASSPETUGAS.setText("");
                }

            } catch (NoResultException e) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                jTextFieldNAMAPETUGAS.requestFocus();
            }

            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButtonMASUKPETUGASActionPerformed

    private void jTextFieldNAMAPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNAMAPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNAMAPETUGASActionPerformed

    private void jCheckBoxPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPASSActionPerformed
        if (jCheckBoxPASS.isSelected()) {
            jTextFieldPASSPETUGAS.setEchoChar((char) 0);
        } else {
            jTextFieldPASSPETUGAS.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPASSActionPerformed

    private void jTextFieldPASSPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPASSPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPASSPETUGASActionPerformed

    private void jLabelLUPASANDIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLUPASANDIMouseClicked
        LUPASANDIPETUGAS l = new LUPASANDIPETUGAS();
        l.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabelLUPASANDIMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMASUKPETUGAS;
    private javax.swing.JCheckBox jCheckBoxPASS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLUPASANDI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNAMAPETUGAS;
    private javax.swing.JPasswordField jTextFieldPASSPETUGAS;
    // End of variables declaration//GEN-END:variables
}
