/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Login.ROLEMASUK;

/**
 *
 * @author HP
 */
public class MENUPETUGAS extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public MENUPETUGAS() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDATAMITRA = new javax.swing.JLabel();
        jLabelDATAPETUGAS = new javax.swing.JLabel();
        jLabelPENGOLAHAN = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPENJUALANMITRA = new javax.swing.JLabel();
        jLabelINPUTSETORANSAMPAH = new javax.swing.JLabel();
        jLabelKELOLAJENISSAMPAH = new javax.swing.JLabel();
        jLabelKELOLANASABAH = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDATAMITRA.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDATAMITRA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelDATAMITRA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDATAMITRA.setText("Kelola Data Mitra");
        jLabelDATAMITRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDATAMITRAMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDATAMITRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, 60));

        jLabelDATAPETUGAS.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDATAPETUGAS.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelDATAPETUGAS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDATAPETUGAS.setText("Kelola Data Petugas");
        jLabelDATAPETUGAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDATAPETUGASMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDATAPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, 60));

        jLabelPENGOLAHAN.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPENGOLAHAN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelPENGOLAHAN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPENGOLAHAN.setText("Stok & Pengolahan Sampah");
        jLabelPENGOLAHAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPENGOLAHANMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPENGOLAHAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 50));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BANK SAMPAH");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, -10, -1, 80));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MENU PETUGAS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 166.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabelPENJUALANMITRA.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPENJUALANMITRA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelPENJUALANMITRA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPENJUALANMITRA.setText("Penjualan Ke Mitra");
        jLabelPENJUALANMITRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPENJUALANMITRAMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPENJUALANMITRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, 60));

        jLabelINPUTSETORANSAMPAH.setBackground(new java.awt.Color(0, 0, 0));
        jLabelINPUTSETORANSAMPAH.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelINPUTSETORANSAMPAH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelINPUTSETORANSAMPAH.setText("Input Setoran Sampah");
        jLabelINPUTSETORANSAMPAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelINPUTSETORANSAMPAHMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelINPUTSETORANSAMPAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, 60));

        jLabelKELOLAJENISSAMPAH.setBackground(new java.awt.Color(0, 0, 0));
        jLabelKELOLAJENISSAMPAH.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelKELOLAJENISSAMPAH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKELOLAJENISSAMPAH.setText("Kelola Jenis Sampah");
        jLabelKELOLAJENISSAMPAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKELOLAJENISSAMPAHMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelKELOLAJENISSAMPAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, 60));

        jLabelKELOLANASABAH.setBackground(new java.awt.Color(0, 0, 0));
        jLabelKELOLANASABAH.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelKELOLANASABAH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKELOLANASABAH.setText("Kelola Data Nasabah");
        jLabelKELOLANASABAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKELOLANASABAHMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelKELOLANASABAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 80));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 153 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelKELOLANASABAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKELOLANASABAHMouseClicked
        KELOLANASABAH y = new KELOLANASABAH();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelKELOLANASABAHMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ROLEMASUK y = new ROLEMASUK();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabelINPUTSETORANSAMPAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelINPUTSETORANSAMPAHMouseClicked
        inputsetoranNASABAH y = new inputsetoranNASABAH();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelINPUTSETORANSAMPAHMouseClicked

    private void jLabelKELOLAJENISSAMPAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKELOLAJENISSAMPAHMouseClicked
        KELOLAJENISSAMPAH y = new KELOLAJENISSAMPAH();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelKELOLAJENISSAMPAHMouseClicked

    private void jLabelPENGOLAHANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPENGOLAHANMouseClicked
        PENYIMPANANGUDANG y = new PENYIMPANANGUDANG();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelPENGOLAHANMouseClicked

    private void jLabelPENJUALANMITRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPENJUALANMITRAMouseClicked
        PENJUALANKEMITRA y = new PENJUALANKEMITRA();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelPENJUALANMITRAMouseClicked

    private void jLabelDATAPETUGASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDATAPETUGASMouseClicked
        DATAPETUGAS y = new DATAPETUGAS();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelDATAPETUGASMouseClicked

    private void jLabelDATAMITRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDATAMITRAMouseClicked
        DATAMITRAJUAL y = new DATAMITRAJUAL();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelDATAMITRAMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        DOMPETBANKSAMPAH y = new DOMPETBANKSAMPAH(this, true);
        y.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUPETUGAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUPETUGAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUPETUGAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUPETUGAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUPETUGAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDATAMITRA;
    private javax.swing.JLabel jLabelDATAPETUGAS;
    private javax.swing.JLabel jLabelINPUTSETORANSAMPAH;
    private javax.swing.JLabel jLabelKELOLAJENISSAMPAH;
    private javax.swing.JLabel jLabelKELOLANASABAH;
    private javax.swing.JLabel jLabelPENGOLAHAN;
    private javax.swing.JLabel jLabelPENJUALANMITRA;
    // End of variables declaration//GEN-END:variables
}
