/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Login.ROLEMASUK;
import Login.LIHATSALDO;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MENUNASABAH extends javax.swing.JFrame {

    private int idNasabah;
    private Nasabah nasabahLogin;
    
    private EntityManagerFactory emf;
    private EntityManager em;

    /**
     * Constructor dengan Parameter ID
     */
    public MENUNASABAH(int idNasabah) {
        initComponents();
        this.idNasabah = idNasabah;

        connect(); // Pastikan koneksi DB jalan dulu

        // 2. AMBIL DATA DARI DATABASE (PENTING!)
        // Cari data nasabah berdasarkan ID yang dikirim
        try {
            this.nasabahLogin = em.find(Nasabah.class, idNasabah);
        } catch (Exception e) {
            System.out.println("Gagal ambil data nasabah: " + e.getMessage());
        }

        // 3. Baru tampilkan namanya
        tampilNamaNasabah();

        setLocationRelativeTo(null);
    }
   
    public MENUNASABAH(Nasabah nasabah) {
        initComponents();
        this.nasabahLogin = nasabah; // Simpan data yang dikirim
        this.idNasabah = nasabah.getIdNasabah(); // Simpan ID juga buat jaga-jaga
        
        tampilNamaNasabah(); // Tampilkan nama di layar
        setLocationRelativeTo(null);
    }
    // --------------------------------------------------

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public void tampilNamaNasabah() {
        if (nasabahLogin != null) {
           
            jLabelNASABAHLOGIN.setText(nasabahLogin.getNamaNasabah()); 
        } else {
            System.out.println("Data nasabah null!");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRIWAYATSETORAN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelNASABAHLOGIN = new javax.swing.JLabel();
        jLabelLIHATSALDO = new javax.swing.JLabel();
        jLabelNASABAHLOGIN1 = new javax.swing.JLabel();
        jLabelTARIKSALDO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KELUAR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRIWAYATSETORAN.setBackground(new java.awt.Color(0, 0, 0));
        jLabelRIWAYATSETORAN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelRIWAYATSETORAN.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRIWAYATSETORAN.setText("RIWAYAT PENARIKAN");
        jLabelRIWAYATSETORAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRIWAYATSETORANMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRIWAYATSETORAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jLabelNASABAHLOGIN.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNASABAHLOGIN.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabelNASABAHLOGIN.setForeground(new java.awt.Color(0, 51, 0));
        jLabelNASABAHLOGIN.setText("JLABEL");
        getContentPane().add(jLabelNASABAHLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, -1, 80));

        jLabelLIHATSALDO.setBackground(new java.awt.Color(0, 0, 0));
        jLabelLIHATSALDO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLIHATSALDO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLIHATSALDO.setText("Lihat Saldo");
        jLabelLIHATSALDO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLIHATSALDOMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelLIHATSALDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, -1, 60));

        jLabelNASABAHLOGIN1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNASABAHLOGIN1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabelNASABAHLOGIN1.setForeground(new java.awt.Color(0, 51, 0));
        jLabelNASABAHLOGIN1.setText("Selamat Datang ,                ");
        getContentPane().add(jLabelNASABAHLOGIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, -1, 80));

        jLabelTARIKSALDO.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTARIKSALDO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTARIKSALDO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTARIKSALDO.setText("Tarik Saldo");
        jLabelTARIKSALDO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTARIKSALDOMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTARIKSALDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 118 (2).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 480, 400));

        KELUAR.setBackground(new java.awt.Color(0, 0, 0));
        KELUAR.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        KELUAR.setForeground(new java.awt.Color(51, 102, 0));
        KELUAR.setText("Keluar");
        KELUAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KELUARMouseClicked(evt);
            }
        });
        getContentPane().add(KELUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 127, 83));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANK SAMPAH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 80));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MENU NASABAH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Rectangle 119.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Gemini_Generated_Image_wx0vwewx0vwewx0v (1) 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KELUARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KELUARMouseClicked
        ROLEMASUK y = new ROLEMASUK();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KELUARMouseClicked

    private void jLabelLIHATSALDOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLIHATSALDOMouseClicked
        int id = idNasabah;

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        Nasabah nasabah = em.find(Nasabah.class, id);

        LIHATSALDO ls = new LIHATSALDO(this, true, nasabah);
        ls.setVisible(true);

        em.close();
        emf.close();

    }//GEN-LAST:event_jLabelLIHATSALDOMouseClicked

    private void jLabelRIWAYATSETORANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRIWAYATSETORANMouseClicked
        RIWAYATTARIKSALDONASABAH y = new RIWAYATTARIKSALDONASABAH(nasabahLogin);
        y.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelRIWAYATSETORANMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        ROLEMASUK y = new ROLEMASUK();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabelTARIKSALDOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTARIKSALDOMouseClicked
        int id = idNasabah;

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        Nasabah nasabah = em.find(Nasabah.class, id);

        tariksaldoNASABAH ts = new tariksaldoNASABAH(this, true, nasabah);
        ts.setVisible(true);

        em.close();
        emf.close();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelTARIKSALDOMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MENUNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MENUNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MENUNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MENUNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MENUNASABAH().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KELUAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLIHATSALDO;
    private javax.swing.JLabel jLabelNASABAHLOGIN;
    private javax.swing.JLabel jLabelNASABAHLOGIN1;
    private javax.swing.JLabel jLabelRIWAYATSETORAN;
    private javax.swing.JLabel jLabelTARIKSALDO;
    // End of variables declaration//GEN-END:variables
}
