/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Login.JenisSampah;
import Login.MENUPETUGAS;
import Login.MitraJual;
import Login.Nasabah;
import Login.Pengolahan;
import Login.PenjualanMitra;
import Login.Petugas;
import Login.Setoran;
import Login.Saldo;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class PENJUALANKEMITRA extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    public PENJUALANKEMITRA() {
        initComponents();
        connect();
        loadComboPetugas();
        loadComboMitra();
        loadComboHasilPengolahan();
        setTanggalHariIni();

        // Panggil autoID agar field ID terisi otomatis saat form dibuka
        jTextIDPENGOLAHAN.setText(String.valueOf(autoID()));
        jTextIDPENGOLAHAN.setEditable(false); // Biar tidak bisa diedit manual

        setLocationRelativeTo(null);
    }

    private void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    private void loadComboPetugas() {
        try {
            List<Petugas> list = em.createNamedQuery("Petugas.findAll", Petugas.class).getResultList();
            jComboBoxPETUGAS1.removeAllItems();
            jComboBoxPETUGAS1.addItem(null);
            for (Petugas p : list) {
                jComboBoxPETUGAS1.addItem(p);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load petugas: " + e.getMessage());
        }
    }

    private void loadComboMitra() {
        try {
            List<MitraJual> list = em.createNamedQuery("MitraJual.findAll", MitraJual.class).getResultList();
            jComboBoxNAMAMITRA.removeAllItems();
            jComboBoxNAMAMITRA.addItem(null);
            for (MitraJual m : list) {
                jComboBoxNAMAMITRA.addItem(m);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load mitra: " + e.getMessage());
        }
    }

    private void loadComboHasilPengolahan() {
        try {
            List<Pengolahan> list = em.createNamedQuery("Pengolahan.findAll", Pengolahan.class).getResultList();
            jComboBoxHASILPENGOLAHAN.removeAllItems();
            jComboBoxHASILPENGOLAHAN.addItem(null);
            for (Pengolahan h : list) {
                jComboBoxHASILPENGOLAHAN.addItem(h);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load hasil pengolahan: " + e.getMessage());
        }
    }

    private void setTanggalHariIni() {
        jTextTANGGALPENJUALAN.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }

    private void bersih() {
        jTextBERATPENJUALAN.setText("");
        jTextTOTALHARGA.setText("");
        jComboBoxNAMAMITRA.setSelectedIndex(0);
        jComboBoxPETUGAS1.setSelectedIndex(0);
        jComboBoxHASILPENGOLAHAN.setSelectedIndex(0);
        setTanggalHariIni();
    }

    private int autoID() {
        int id = 1; // Default ID awal jika tabel kosong
        try {
            // Ambil ID terbesar (MAX) dari tabel PenjualanMitra
            // Bukan ambil semua list, tapi cukup 1 angka terbesar saja
            Integer maxID = em.createQuery(
                    "SELECT MAX(p.idPenjualanMitra) FROM PenjualanMitra p", Integer.class)
                    .getSingleResult();

            if (maxID != null) {
                id = maxID + 1; // Tambahkan 1 dari ID terakhir
            }
        } catch (Exception e) {

        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jToggleBATAL = new javax.swing.JToggleButton();
        jComboBoxHASILPENGOLAHAN = new javax.swing.JComboBox();
        jToggleJUAL = new javax.swing.JToggleButton();
        jTextTANGGALPENJUALAN = new javax.swing.JTextField();
        jTextTOTALHARGA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextBERATPENJUALAN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextIDPENGOLAHAN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxNAMAMITRA = new javax.swing.JComboBox();
        jToggleCEKRIWAYATPENJUALAN = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxPETUGAS1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nasabah");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleBATAL.setBackground(new java.awt.Color(153, 0, 0));
        jToggleBATAL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleBATAL.setForeground(new java.awt.Color(255, 255, 255));
        jToggleBATAL.setText("BATAL");
        jToggleBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBATALActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleBATAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, 30));

        jComboBoxHASILPENGOLAHAN.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxHASILPENGOLAHAN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxHASILPENGOLAHAN.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxHASILPENGOLAHAN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBoxHASILPENGOLAHAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 290, 40));

        jToggleJUAL.setBackground(new java.awt.Color(0, 51, 0));
        jToggleJUAL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleJUAL.setForeground(new java.awt.Color(255, 255, 255));
        jToggleJUAL.setText("JUAL");
        jToggleJUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleJUALActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleJUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 100, 30));

        jTextTANGGALPENJUALAN.setBackground(new java.awt.Color(255, 255, 255));
        jTextTANGGALPENJUALAN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextTANGGALPENJUALAN.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextTANGGALPENJUALAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 40));

        jTextTOTALHARGA.setBackground(new java.awt.Color(255, 255, 255));
        jTextTOTALHARGA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextTOTALHARGA.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextTOTALHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 290, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Harga");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal Penjualan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Berat Penjualan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Mitra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hasil Pengolahan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 20));

        jTextBERATPENJUALAN.setBackground(new java.awt.Color(255, 255, 255));
        jTextBERATPENJUALAN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextBERATPENJUALAN.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextBERATPENJUALAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 290, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Penjualan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jTextIDPENGOLAHAN.setBackground(new java.awt.Color(255, 255, 255));
        jTextIDPENGOLAHAN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextIDPENGOLAHAN.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextIDPENGOLAHAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 127, 83));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PENJUALAN HASIL OLAH SAMPAH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        jComboBoxNAMAMITRA.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxNAMAMITRA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxNAMAMITRA.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNAMAMITRA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBoxNAMAMITRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 260, 40));

        jToggleCEKRIWAYATPENJUALAN.setBackground(new java.awt.Color(0, 51, 0));
        jToggleCEKRIWAYATPENJUALAN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleCEKRIWAYATPENJUALAN.setForeground(new java.awt.Color(255, 255, 255));
        jToggleCEKRIWAYATPENJUALAN.setText("RIWAYAT PENJUALAN");
        jToggleCEKRIWAYATPENJUALAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleCEKRIWAYATPENJUALANActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleCEKRIWAYATPENJUALAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 190, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANK SAMPAH - PENJUALAN MITRA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 149.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID Pengolahan");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jComboBoxPETUGAS1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPETUGAS1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxPETUGAS1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxPETUGAS1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBoxPETUGAS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 330, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Hasil Pengolahan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        MENUPETUGAS z = new MENUPETUGAS();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jToggleBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jToggleBATALActionPerformed

    private void jToggleJUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleJUALActionPerformed

        try {
            // ===========================
            // 1. VALIDASI INPUT
            // ===========================
            if (jComboBoxNAMAMITRA.getSelectedItem() == null
                    || jComboBoxHASILPENGOLAHAN.getSelectedItem() == null
                    || jTextBERATPENJUALAN.getText().trim().isEmpty()
                    || jTextTOTALHARGA.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Semua data (Mitra, Produk, Berat, Total) harus dilengkapi!");
                return;
            }

            // ===========================
            // 2. AMBIL DATA DARI FORM
            // ===========================
            MitraJual mitra = (MitraJual) jComboBoxNAMAMITRA.getSelectedItem();
            Pengolahan pengolahanDipilih = (Pengolahan) jComboBoxHASILPENGOLAHAN.getSelectedItem();
            JenisSampah jenisProduk = pengolahanDipilih.getIdJenissampah();

            // Parsing Angka
            BigInteger beratJual = new BigInteger(jTextBERATPENJUALAN.getText());
            BigInteger totalHarga = new BigInteger(jTextTOTALHARGA.getText());
            Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(jTextTANGGALPENJUALAN.getText());

            // ===========================
            // 3. CEK STOK GUDANG 
            // ===========================
            StokGudang stokBarangJadi = null;
            // Query to find stock for the specific waste type with status "Hasil Pengolahan"
            List<StokGudang> daftarStok = em.createQuery(
                    "SELECT s FROM StokGudang s WHERE s.idJenissampah.idJenissampah = :id "
                    + "AND s.statusStok = :status AND s.beratTersedia > 0", StokGudang.class)
                    .setParameter("id", jenisProduk.getIdJenissampah())
                    .setParameter("status", "Hasil Pengolahan")
                    .getResultList();

            if (daftarStok.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Stok Kosong for " + jenisProduk.getNamaSampah());
                return;
            }

            int beratJualInt = beratJual.intValue();

            // Find a batch with enough stock
            for (StokGudang s : daftarStok) {
                if (s.getBeratTersedia() >= beratJualInt) {
                    stokBarangJadi = s;
                    break;
                }
            }

            if (stokBarangJadi == null) {
                JOptionPane.showMessageDialog(this, "Stok tidak mencukupi for this transaction!");
                return;
            }

            // ===========================
            // 4. PROSES SIMPAN (FIX DUPLICATE ID)
            // ===========================
            em.getTransaction().begin();

            PenjualanMitra p = new PenjualanMitra();

            // --- PERBAIKAN UTAMA DISINI ---
            // Always generate a NEW ID. Do not rely on the text field which might show an old ID.
            int idBaru = autoID();
            p.setIdPenjualanMitra(idBaru);
            // ------------------------------

            p.setTanggalPenjualanMitra(tanggal);
            p.setBeratKgPenjualanMitra(beratJual);
            p.setTotalHargaPenjualanMitra(totalHarga);
            p.setIdMitra(mitra);
            p.setIdPengolahan(pengolahanDipilih);

            em.persist(p);

            // Update Stok
            int sisa = stokBarangJadi.getBeratTersedia() - beratJualInt;
            stokBarangJadi.setBeratTersedia(sisa);

            // If stock becomes 0, change status (optional but good practice)
            if (sisa <= 0) {
                stokBarangJadi.setStatusStok("Terjual");
            }
            em.merge(stokBarangJadi);

            // ================================================================
            // C. UPDATE KAS BANK (BERTAMBAH / UANG MASUK)
            // ================================================================
            // Ambil Dompet Bank ID 1
            DompetBankSampah_1 dompet = em.find(DompetBankSampah_1.class, 1);

            if (dompet != null) {
                // Refresh data biar terbaru
                em.refresh(dompet);

                // Konversi BigInteger (Form) ke long (Entity)
                long hargaJualLong = totalHarga.longValue();

                // Rumus: Saldo Lama + Pendapatan Baru
                long saldoBaru = dompet.getTotalKasBank() + hargaJualLong;

                // Set saldo baru
                dompet.setTotalKasBank(saldoBaru);
                dompet.setTerakhirDiupdate(new Date());

                em.merge(dompet);
            } else {
                // Jika dompet belum ada, bisa pilih mau error atau buat baru
                // Disini saya buatkan peringatan saja agar admin isi modal dulu
                JOptionPane.showMessageDialog(this, "Peringatan: Dompet Bank ID 1 tidak ditemukan. Saldo tidak bertambah.");
            }
            // ================================================================

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Penjualan Berhasil! Stok berkurang & Kas Bank bertambah.");

            bersih();

            // Tampilkan ID selanjutnya di text field untuk info user (visual feedback only)
            jTextIDPENGOLAHAN.setText(String.valueOf(autoID()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            e.printStackTrace();
        }

    }//GEN-LAST:event_jToggleJUALActionPerformed

    private void jToggleCEKRIWAYATPENJUALANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleCEKRIWAYATPENJUALANActionPerformed
        RIWAYATMITRAJUAL l = new RIWAYATMITRAJUAL();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleCEKRIWAYATPENJUALANActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PENGOLAHANSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PENGOLAHANSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PENGOLAHANSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PENGOLAHANSAMPAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PENGOLAHANSAMPAH().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxHASILPENGOLAHAN;
    private javax.swing.JComboBox jComboBoxNAMAMITRA;
    private javax.swing.JComboBox jComboBoxPETUGAS1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextBERATPENJUALAN;
    private javax.swing.JTextField jTextIDPENGOLAHAN;
    private javax.swing.JTextField jTextTANGGALPENJUALAN;
    private javax.swing.JTextField jTextTOTALHARGA;
    private javax.swing.JToggleButton jToggleBATAL;
    private javax.swing.JToggleButton jToggleCEKRIWAYATPENJUALAN;
    private javax.swing.JToggleButton jToggleJUAL;
    // End of variables declaration//GEN-END:variables
}
