/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */
package Login;

/**
 *
 * @author HP
 */
public class ROLEMASUK extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public ROLEMASUK() {
        initComponents();
        setLocationRelativeTo(null);
    }

//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */ * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelMASUKPETUGAS = new javax.swing.JLabel();
        jlabelMASUKPNASABAH = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelMASUKPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jlabelMASUKPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        jlabelMASUKPETUGAS.setText("MASUK PETUGAS");
        jlabelMASUKPETUGAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelMASUKPETUGASMouseClicked(evt);
            }
        });
        getContentPane().add(jlabelMASUKPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jlabelMASUKPNASABAH.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jlabelMASUKPNASABAH.setForeground(new java.awt.Color(0, 0, 0));
        jlabelMASUKPNASABAH.setText("MASUK NASABAH");
        jlabelMASUKPNASABAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelMASUKPNASABAHMouseClicked(evt);
            }
        });
        getContentPane().add(jlabelMASUKPNASABAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Silahkan masuk dan pilih peran anda :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SELAMAT DATANG!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 52)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APLIKASI BANK SAMPAH");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 127, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 165 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabelMASUKPETUGASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelMASUKPETUGASMouseClicked
        MASUKPETUGAS dialog = new MASUKPETUGAS(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jlabelMASUKPETUGASMouseClicked

    private void jlabelMASUKPNASABAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelMASUKPNASABAHMouseClicked
        MASUKNASABAH dialog = new MASUKNASABAH(this, true);
        dialog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlabelMASUKPNASABAHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROLEMASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROLEMASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROLEMASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROLEMASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROLEMASUK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabelMASUKPETUGAS;
    private javax.swing.JLabel jlabelMASUKPNASABAH;
    // End of variables declaration//GEN-END:variables
}
