/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import java.math.BigInteger;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class tambahKELOLAHJENISSAMPAH extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    public tambahKELOLAHJENISSAMPAH(KELOLAJENISSAMPAH parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect();
        loadComboKategori();
        getNextIdJenisSampah();
        setLocationRelativeTo(null);
    }

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    private void loadComboKategori() {
        jComboBoxKategori.removeAllItems();
        jComboBoxKategori.addItem("--Pilih Kategori--");
        jComboBoxKategori.addItem("Organik");
        jComboBoxKategori.addItem("Anorganik");
        jComboBoxKategori.addItem("B3");
    }

    public void bersih() {
        textIDJENISSAMPAH.setText("");
        textNAMAsampah.setText("");
        jComboBoxKategori.setSelectedIndex(0);
        textHARGAPERKG.setText("");
    }

    private boolean validasiInput() {
        if (textNAMAsampah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama sampah harus diisi");
            textNAMAsampah.requestFocus();
            return false;
        }
        if (jComboBoxKategori.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Kategori harus dipilih");
            jComboBoxKategori.requestFocus();
            return false;
        }
        String hargaText = textHARGAPERKG.getText().trim();
        if (!hargaText.isEmpty()) {
            try {
                new BigInteger(hargaText);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Harga per KG harus berupa angka");
                textHARGAPERKG.requestFocus();
                return false;
            }
        }
        return true;
    }

    private Integer getNextIdJenisSampah() {
        try {
            Integer next = em.createQuery(
                    "SELECT COALESCE(MAX(j.idJenissampah), 0) + 1 FROM JenisSampah j", Integer.class)
                    .getSingleResult();
            return next;
        } catch (Exception ex) {
            return 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textHARGAPERKG = new javax.swing.JTextField();
        textNAMAsampah = new javax.swing.JTextField();
        textIDJENISSAMPAH = new javax.swing.JTextField();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxKategori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textHARGAPERKG.setBackground(new java.awt.Color(204, 255, 153));
        textHARGAPERKG.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textHARGAPERKG.setForeground(new java.awt.Color(0, 0, 0));
        textHARGAPERKG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textHARGAPERKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHARGAPERKGActionPerformed(evt);
            }
        });
        getContentPane().add(textHARGAPERKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 420, 40));

        textNAMAsampah.setBackground(new java.awt.Color(204, 255, 153));
        textNAMAsampah.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textNAMAsampah.setForeground(new java.awt.Color(0, 0, 0));
        textNAMAsampah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textNAMAsampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNAMAsampahActionPerformed(evt);
            }
        });
        getContentPane().add(textNAMAsampah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 420, 40));

        textIDJENISSAMPAH.setBackground(new java.awt.Color(204, 255, 153));
        textIDJENISSAMPAH.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textIDJENISSAMPAH.setForeground(new java.awt.Color(0, 0, 0));
        textIDJENISSAMPAH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textIDJENISSAMPAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDJENISSAMPAHActionPerformed(evt);
            }
        });
        getContentPane().add(textIDJENISSAMPAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 410, 40));

        jButtonSIMPAN.setBackground(new java.awt.Color(0, 51, 0));
        jButtonSIMPAN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 130, 40));

        jButtonBATAL.setBackground(new java.awt.Color(0, 51, 0));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBATAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Kategori");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID Jenis Sampah");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Sampah");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Harga Per KG");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BANK SAMPAH - KELOLA SAMPAH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 127, 80));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TAMBAH DATA SAMPAH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jComboBoxKategori.setBackground(new java.awt.Color(204, 255, 153));
        jComboBoxKategori.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 420, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 149.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHARGAPERKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHARGAPERKGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHARGAPERKGActionPerformed

    private void textNAMAsampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNAMAsampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNAMAsampahActionPerformed

    private void textIDJENISSAMPAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDJENISSAMPAHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDJENISSAMPAHActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        try {
            if (!validasiInput()) {
                return;
            }
            if (em == null || !em.isOpen()) {
                JOptionPane.showMessageDialog(this, "Koneksi belum siap.");
                return;
            }

            String idText = textIDJENISSAMPAH.getText().trim();
            String nama = textNAMAsampah.getText().trim();
            String kategori = jComboBoxKategori.getSelectedItem().toString();
            String hargaText = textHARGAPERKG.getText().trim();

            em.getTransaction().begin();
            JenisSampah js = new JenisSampah();

            if (!idText.isEmpty()) {
                js.setIdJenissampah(Integer.parseInt(idText));
            } else {
                js.setIdJenissampah(getNextIdJenisSampah());
            }

            js.setNamaSampah(nama);
            js.setKategori(kategori);
            if (!hargaText.isEmpty()) {
                js.setHargaPerKg(new BigInteger(hargaText));
            }

            em.persist(js);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            this.dispose();
            bersih();

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        bersih();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBoxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(insertkelolanasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                insertkelolanasabah dialog = new insertkelolanasabah(new javax.swing.JFrame(), true);
////                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
////                    @Override
////                    public void windowClosing(java.awt.event.WindowEvent e) {
////                        System.exit(0);
////                    }
////                });
////                dialog.setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JComboBox jComboBoxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textHARGAPERKG;
    private javax.swing.JTextField textIDJENISSAMPAH;
    private javax.swing.JTextField textNAMAsampah;
    // End of variables declaration//GEN-END:variables
}
