/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import Login.Petugas;
import Login.Saldo;
import java.awt.Frame;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class tambahDATAPETUGAS extends javax.swing.JDialog {

    /**
     * Creates new form INSERTKELOLANASABAH
     */
    private EntityManagerFactory emf;
    private EntityManager em;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public tambahDATAPETUGAS(DATAPETUGAS parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect();

        // --- TAMBAHAN ---
        textIDPETUGAS.setText(String.valueOf(autoID())); // Tampilkan ID calon baru
        textIDPETUGAS.setEditable(false); // Matikan agar tidak bisa diketik manual
        // ----------------

        setLocationRelativeTo(null);
    }

    private boolean validasiInput() {
        if (textIDPETUGAS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Petugas harus diisi");
            textIDPETUGAS.requestFocus();
            return false;
        }
        if (textNAMAPETUGAS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Petugas harus diisi");
            textNAMAPETUGAS.requestFocus();
            return false;
        }
        if (textNAMAPENGGUNAPETUGAS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pengguna harus diisi");
            textNAMAPENGGUNAPETUGAS.requestFocus();
            return false;
        }
        if (textKATASANDIPETUGAS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kata sandi harus diisi");
            textKATASANDIPETUGAS.requestFocus();
            return false;
        }
        return true;
    }

    public int autoID() {
        int id = 1; // Default ID awal
        try {
            // Ambil ID Petugas terbesar (MAX) dari database
            Integer maxID = em.createQuery(
                    "SELECT MAX(p.idPetugas) FROM Petugas p", Integer.class)
                    .getSingleResult();

            if (maxID != null) {
                id = maxID + 1; // Tambahkan 1 dari ID terakhir
            }
        } catch (Exception e) {
            System.out.println("Tabel kosong atau error: " + e.getMessage());
        }
        return id;
    }

    public void bersih() {
        textIDPETUGAS.setText("");
        textNAMAPETUGAS.setText("");
        textNAMAPENGGUNAPETUGAS.setText("");
        textKATASANDIPETUGAS.setText("");
        textNAMAIBUPETUGAS.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNAMAPETUGAS = new javax.swing.JTextField();
        textIDPETUGAS = new javax.swing.JTextField();
        textNAMAPENGGUNAPETUGAS = new javax.swing.JTextField();
        textKATASANDIPETUGAS = new javax.swing.JTextField();
        textNAMAIBUPETUGAS = new javax.swing.JTextField();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNAMAPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        textNAMAPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textNAMAPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        textNAMAPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textNAMAPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNAMAPETUGASActionPerformed(evt);
            }
        });
        getContentPane().add(textNAMAPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 40));

        textIDPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        textIDPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textIDPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        textIDPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textIDPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDPETUGASActionPerformed(evt);
            }
        });
        getContentPane().add(textIDPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 270, 40));

        textNAMAPENGGUNAPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        textNAMAPENGGUNAPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textNAMAPENGGUNAPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        textNAMAPENGGUNAPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textNAMAPENGGUNAPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNAMAPENGGUNAPETUGASActionPerformed(evt);
            }
        });
        getContentPane().add(textNAMAPENGGUNAPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 40));

        textKATASANDIPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        textKATASANDIPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textKATASANDIPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        textKATASANDIPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textKATASANDIPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKATASANDIPETUGASActionPerformed(evt);
            }
        });
        getContentPane().add(textKATASANDIPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 270, 40));

        textNAMAIBUPETUGAS.setBackground(new java.awt.Color(204, 255, 153));
        textNAMAIBUPETUGAS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        textNAMAIBUPETUGAS.setForeground(new java.awt.Color(0, 0, 0));
        textNAMAIBUPETUGAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textNAMAIBUPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNAMAIBUPETUGASActionPerformed(evt);
            }
        });
        getContentPane().add(textNAMAIBUPETUGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 270, 40));

        jButtonSIMPAN.setBackground(new java.awt.Color(0, 51, 0));
        jButtonSIMPAN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 130, 40));

        jButtonBATAL.setBackground(new java.awt.Color(0, 51, 0));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBATAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 150.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama Ibu Petugas");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kata Sandi Petugas");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID Petugas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Petugas");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Pengguna Petugas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BANK SAMPAH - KELOLA NASABAH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 127, 80));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TAMBAH DATA PETUGAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 149.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNAMAPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNAMAPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNAMAPETUGASActionPerformed

    private void textIDPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDPETUGASActionPerformed

    private void textNAMAPENGGUNAPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNAMAPENGGUNAPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNAMAPENGGUNAPETUGASActionPerformed

    private void textKATASANDIPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKATASANDIPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKATASANDIPETUGASActionPerformed

    private void textNAMAIBUPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNAMAIBUPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNAMAIBUPETUGASActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed

        try {
            // Validasi Input Kosong (Kecuali ID, karena ID otomatis)
            if (textNAMAPETUGAS.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi Nama Petugas!");
            } else if (textNAMAPENGGUNAPETUGAS.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi Username Petugas!");
            } else if (textKATASANDIPETUGAS.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi Password Petugas!");
            } else if (textNAMAIBUPETUGAS.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi Nama Ibu!");
            } else {

                // Mulai Transaksi
                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();

                Petugas p = new Petugas();

                // === PERBAIKAN PENTING DI SINI ===
                // Jangan ambil dari Text Field, tapi panggil fungsi autoID() lagi 
                // untuk memastikan ID benar-benar baru dan unik saat detik penyimpanan.
                p.setIdPetugas(autoID());
                // =================================

                p.setNamaPetugas(textNAMAPETUGAS.getText());
                p.setUsernamePetugas(textNAMAPENGGUNAPETUGAS.getText());
                p.setPasswordPetugas(textKATASANDIPETUGAS.getText());
                p.setNamaIbu(textNAMAIBUPETUGAS.getText());

                em.persist(p);
                em.getTransaction().commit();

                // Tutup EntityManager
                em.close();

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

                bersih();
                dispose(); // Tutup form tambah
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Simpan gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        bersih();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(editkelolaNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(editkelolaNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(editkelolaNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(editkelolaNASABAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                editkelolaNASABAH dialog = new editkelolaNASABAH(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textIDPETUGAS;
    private javax.swing.JTextField textKATASANDIPETUGAS;
    private javax.swing.JTextField textNAMAIBUPETUGAS;
    private javax.swing.JTextField textNAMAPENGGUNAPETUGAS;
    private javax.swing.JTextField textNAMAPETUGAS;
    // End of variables declaration//GEN-END:variables
}
