/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Login;

import Login.Penarikan;
import java.math.BigInteger;
import java.sql.DriverManager;
import java.text.NumberFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

//*
// * @author H
//
public class tariksaldoNASABAH extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;
    private Nasabah nasabah;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    NumberFormat kursIDR = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

    public tariksaldoNASABAH(java.awt.Frame parent, boolean modal, Nasabah nasabah) {
        super(parent, modal);
        initComponents();
        this.nasabah = nasabah;

        jTextFieldTANGGALPENARIKAN.setText(sdf.format(new Date()));
        jTextFieldTANGGALPENARIKAN.setEditable(false);

        jComboBoxPILIHMETODE();

        tampilSaldo();

        setLocationRelativeTo(null);
    }

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public void jComboBoxPILIHMETODE() {
        jComboBoxPILIHMETODE.removeAllItems();
        jComboBoxPILIHMETODE.addItem("--Pilih Metode--");
        jComboBoxPILIHMETODE.addItem("Cash");
        jComboBoxPILIHMETODE.addItem("Transfer Bank");
        jComboBoxPILIHMETODE.addItem("E-Wallet (Dana/OVO/Gopay)");
        jComboBoxPILIHMETODE.setSelectedIndex(0);
    }

    private void tampilSaldo() {
        connect();
        try {
            // Ambil data terbaru dari database (agar akurat)
            Nasabah n = em.find(Nasabah.class, nasabah.getIdNasabah());

            // Refresh agar data saldo sinkron dengan DB
            em.refresh(n);

            if (n != null && n.getSaldo() != null) {
                BigInteger saldo = n.getSaldo().getTotalSaldo();

                jLabel3.setText(kursIDR.format(saldo));

                jLabel4.setText(n.getNamaNasabah());

            } else {
                jLabel3.setText("Rp 0");
                jLabel4.setText(n.getNamaNasabah());
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }
    }

    private void cetakStruk() {
        try {
            String path = "src/Login/STRUK SALDO.jasper";
            HashMap<String, Object> parameters = new HashMap<>();

            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BANK_SAMPAH", "postgres", "BISMILLAH");

            JasperPrint jprint = JasperFillManager.fillReport(path, parameters, conn);

            // Setup Viewer
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setSize(800, 600);
            jviewer.setLocationRelativeTo(null); // Tampil di tengah layar
            jviewer.setTitle("Struk Penarikan");

            // --- INI KUNCINYA AGAR MUNCUL DI DEPAN ---
            jviewer.setAlwaysOnTop(true);
            jviewer.toFront();
            jviewer.requestFocus();
            // -----------------------------------------

            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mencetak: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void bersih() {
        jTextFieldJUMLAHPENARIKAN.setText("");
        jComboBoxPILIHMETODE.setSelectedIndex(0);
        jTextFieldJUMLAHPENARIKAN.requestFocus(); // Fokuskan kursor ke input jumlah
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTARIKSALDO = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTANGGALPENARIKAN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldJUMLAHPENARIKAN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxPILIHMETODE = new javax.swing.JComboBox();
        jButtonLIHATRIWAYATSALDO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTARIKSALDO.setBackground(new java.awt.Color(0, 51, 0));
        jButtonTARIKSALDO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonTARIKSALDO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTARIKSALDO.setText("TARIK SALDO");
        jButtonTARIKSALDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTARIKSALDOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTARIKSALDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 160, 30));

        jButtonBATAL.setBackground(new java.awt.Color(255, 51, 51));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBATAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGO BANK SAMPAH.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 127, 83));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 0));
        jLabel9.setText("TARIK SALDO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jTextFieldTANGGALPENARIKAN.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldTANGGALPENARIKAN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldTANGGALPENARIKAN.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldTANGGALPENARIKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("Tanggal Penarikan : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("Pilih Metode : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jTextFieldJUMLAHPENARIKAN.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldJUMLAHPENARIKAN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldJUMLAHPENARIKAN.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldJUMLAHPENARIKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 240, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 0));
        jLabel12.setText("Jumlah Penarikan :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jComboBoxPILIHMETODE.setBackground(new java.awt.Color(0, 51, 51));
        jComboBoxPILIHMETODE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxPILIHMETODE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jComboBoxPILIHMETODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 240, 30));

        jButtonLIHATRIWAYATSALDO.setBackground(new java.awt.Color(102, 153, 0));
        jButtonLIHATRIWAYATSALDO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLIHATRIWAYATSALDO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLIHATRIWAYATSALDO.setText("LIHAT RIWAYAT SALDO");
        jButtonLIHATRIWAYATSALDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLIHATRIWAYATSALDOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLIHATRIWAYATSALDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Group 155.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTARIKSALDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTARIKSALDOActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BANK_SAMPAHPU");
        EntityManager em = emf.createEntityManager();

        try {
            if (jTextFieldJUMLAHPENARIKAN.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan jumlah penarikan!");
                return;
            }
            if (jComboBoxPILIHMETODE.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Pilih metode penarikan dulu!");
                return;
            }

            int jumlahTarik = Integer.parseInt(jTextFieldJUMLAHPENARIKAN.getText());

            if (jumlahTarik < 10000) {
                JOptionPane.showMessageDialog(this, "Minimal penarikan Rp 10.000!");
                return;
            }

            em.getTransaction().begin();

            Nasabah n = em.find(Nasabah.class, nasabah.getIdNasabah());
            em.refresh(n); // Pastikan data saldo paling update

            if (n == null || n.getSaldo() == null) {
                JOptionPane.showMessageDialog(this, "Data Saldo nasabah tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            BigInteger saldoSaatIni = n.getSaldo().getTotalSaldo();
            BigInteger jumlahTarikBI = BigInteger.valueOf(jumlahTarik);

            if (saldoSaatIni.compareTo(jumlahTarikBI) < 0) {
                java.text.NumberFormat kursIDR = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
                JOptionPane.showMessageDialog(this,
                        "Saldo tidak mencukupi!\nSaldo Anda: " + kursIDR.format(saldoSaatIni));
                em.getTransaction().rollback();
                return;
            }

            String inputPin = JOptionPane.showInputDialog(this, "Masukkan PIN Anda untuk konfirmasi:");
            if (inputPin == null) {
                em.getTransaction().rollback();
                return; // User klik Cancel
            }

            if (!inputPin.trim().equals(n.getPasswordNasabah().trim())) {
                JOptionPane.showMessageDialog(this, "PIN salah! Transaksi dibatalkan.");
                em.getTransaction().rollback();
                return;
            }

            BigInteger saldoBaru = saldoSaatIni.subtract(jumlahTarikBI);
            Saldo saldoEntity = n.getSaldo();
            saldoEntity.setTotalSaldo(saldoBaru);

            em.merge(saldoEntity);

            Penarikan p = new Penarikan();
            p.setTanggal(new java.util.Date());
            p.setJumlah(jumlahTarik);
            p.setMetode(jComboBoxPILIHMETODE.getSelectedItem().toString());
            p.setIdNasabah(n);

            em.persist(p);

            em.getTransaction().commit();

            java.text.NumberFormat kursIDR = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
            JOptionPane.showMessageDialog(this,
                    "Penarikan Berhasil!\nSisa Saldo: " + kursIDR.format(saldoBaru));

            jLabel3.setText(kursIDR.format(saldoBaru));

            jTextFieldJUMLAHPENARIKAN.setText("");
            jComboBoxPILIHMETODE.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka valid!");
        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }
    }//GEN-LAST:event_jButtonTARIKSALDOActionPerformed

    private void jButtonLIHATRIWAYATSALDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLIHATRIWAYATSALDOActionPerformed
        RIWAYATTARIKSALDONASABAH r = new RIWAYATTARIKSALDONASABAH(nasabah);
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLIHATRIWAYATSALDOActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LIHATSALDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LIHATSALDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LIHATSALDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LIHATSALDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                LIHATSALDO dialog = new LIHATSALDO(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonLIHATRIWAYATSALDO;
    private javax.swing.JButton jButtonTARIKSALDO;
    private javax.swing.JComboBox jComboBoxPILIHMETODE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldJUMLAHPENARIKAN;
    private javax.swing.JTextField jTextFieldTANGGALPENARIKAN;
    // End of variables declaration//GEN-END:variables
}
